[tool.poetry]
name = "backend-core"
version = "0.1.0"
description = ""
authors = ["Mukund <mukund@Mukunds-MacBook-Air.local>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
